# This file can be consumed by RestClient (VSCode extension)

@server=https://localhost:5001

###
# @name help
GET {{server}}

###
# @name example
GET {{help.response.body.callExample}}

###
# @name invalid
GET {{server}}/HelloWorld/FORM1

###
# @name slack_dialog
POST {{server}}/SlackDialog/{{help.response.body.forms[0]}}
Content-Type: application/json

{
    "CREATEVM_WIN_STRESSALL_ELEMENTS": "text 1",
    "CREATEVM_WIN_STRESSALL_ELEMENTS_1": "text 2",
    "CREATEVM_WIN_STRESSALL_ELEMENTS_2": "2",
    "CREATEVM_WIN_STRESSALL_ELEMENTS_3": "Standard_B2ms"
}

###
# @name slack_block_kit
GET {{server}}/SlackBlockKit/{{help.response.body.forms[0]}}

###
# @name adaptive_cards
GET {{server}}/AdaptiveCards/{{help.response.body.forms[0]}}

###
# @name resource
GET {{help.response.body.definitions}}

